### ISSUE TITLE
Symlinks are treated as regular files

### ISSUE THREAD

**Issue by nokhr** [13pi/iskat#16]
The program does not find the symbolic links by key -l

Example:
al@al-Inspiron-3521:~/iskat/iskat/iskat/src$ ls -l
итого 272
drwxrwxr-x 4 al   al     4096 июля  17 14:35 build
-rw-r----- 1 root root   8160 июля  17 14:45 fi
brw-r--r-- 1 root root   5, 1 июля  17 14:53 fil
-rw-rw-r-- 1 al   al     1246 июля  17 14:34 File.cpp
-rw-rw-r-- 1 al   al     1059 июля  17 14:34 File.h
-rw-rw-r-- 1 al   al      705 июля  17 14:34 filelister.cpp
-rw-rw-r-- 1 al   al        4 июля  17 14:36 file.txt
-rw-rw-r-- 1 al   al     1065 июля  17 14:34 Filter.cpp
-rw-rw-r-- 1 al   al     1179 июля  17 14:34 Filter.h
crw-r--r-- 1 root root   6, 1 июля  17 14:54 fisymb
-rwxrwxr-x 1 al   al   219093 июля  17 14:35 iskat
lrwxrwxrwx 1 al   al        8 июля  17 14:36 link -> file.txt
-rw-rw-r-- 1 al   al     3022 июля  17 14:34 main.cpp
-rw-rw-r-- 1 al   al     1415 июля  17 14:34 makefile
drwxrwxr-x 2 al   al     4096 июля  17 14:34 test
-rw-rw-r-- 1 al   al      440 июля  17 14:34 Walker.cpp
-rw-rw-r-- 1 al   al      402 июля  17 14:34 Walker.h

Try to find symbolic links:
al@al-Inspiron-3521:~/iskat/iskat/iskat/src$ ./iskat --type l
al@al-Inspiron-3521:~/iskat/iskat/iskat/src$

**Comment by VadimAndronov** [comment]
**Done:** 5d82f6fe984f678b338e9827186256491bf27429
