### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by VadimAndronov** [13pi/iskat#3]
### Release notes:
This document should track current product state (e.g, version) and list of enhancements for each next version
### User documentation:
This document should explan how to use product

**Comment by pakozh** [comment]
What about some "internal" documentation?

**Comment by VadimAndronov** [comment]
What about it? Do you really think we need it at this very early stage? Perhaps we'll get one as soon as we need it

**Comment by pakozh** [comment]
We need it right now for describing customer requirements, test-plans, final testing results etc...

**Comment by VadimAndronov** [comment]
__Complete:__ 83a23a3acd454101a391e82dde6daf09d710f5bb
