### ISSUE TITLE
First milestone.

### ISSUE THREAD

**Issue by pakozh** [13pi/iskat#6]
Please, create a milestone for this iteration and assign issues for it.

**Comment by pakozh** [comment]
Responsible person can mark issues as "Closed" when job is done.

**Comment by pakozh** [comment]
Could you please rename first milestone  to something more "practical"? For example Sprint 1, or Iteration 1...

**Comment by VadimAndronov** [comment]
How does "Sprint 1" differ from "First"? Is that really more practical?

**Comment by pakozh** [comment]
It is related to "scrum" terminology. 
https://ru.wikipedia.org/wiki/Scrum
