### ISSUE TITLE
Implement argument parser

### ISSUE THREAD

**Issue by VadimAndronov** [13pi/iskat#9]
Implement command line option parser. Argument parser must compile argv array passed from main function into handy, easy-to-use data structure.
### Options to implement:
* -v , --version
* -h, --help
* --name, --type, --time, --perm, --owner, --group
* --follow-symlink, --max-depth
* --print, --exec

**Comment by pakozh** [comment]
Please, provide -short/--long forms for all types of options.

**Comment by VadimAndronov** [comment]
Some aptions will be ambigous then. For example, -n would have been --name as well as --newer (which is not mentioned here but available in GNU Find)

**Comment by pakozh** [comment]
You can use -n -N or another character. Anyway, now you are choosing both of forms, so you can avoid ambiguity from the beginning. No need to copy  GNU ambiguity.

**Comment by pakozh** [comment]
I promise, we will not implement more options than characters amount of English alphabet :)

**Comment by VadimAndronov** [comment]
**Done:** a0c65bfe4775e808061f2669ce58d6269fa49124
